/*
|============================================
| @Uid generate unique ids
| * Unique ids are generated by using this
| * Add more configurations as you need
|============================================
*/

export function generateUid(
  len: number = 6,
  prefix: string = 'V' /*starts with*/,
) {
  // dataset of characters
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' // only uppercase letters
  let uid = prefix // unique id
  for (let i = 0; i < len - prefix.length; i++) {
    uid += chars.charAt(Math.floor(Math.random() * chars.length)) // generate random characters
  }
  return uid // return unique id
}

/*
|============================================
| @UniqueUsername generate unique usernames
| * Unique names are generated by using this
| * Add more configurations as you need
|============================================
*/
export function generateUsernameHash(prefix: string = 'user_'): string {
  return prefix + (Math.random() * 1000).toString(32).substring(3)
}
